# Generated by Django 2.0.1 on 2018-01-19 18:11

from django.db import migrations, models
import sandbox_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=sandbox_app.models.upload_directory_path, verbose_name='uploaded file'),
        ),
    ]
